# -*- coding: utf-8 -*-
"""lstm_classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15F3z5AxL3p096FgRZdVp07oH0u2pfaik
"""

import os
import torch
import torch.nn as nn

class LSTMBehaviorClassifier(nn.Module):
    def __init__(self, input_size=32, hidden_size=64, num_classes=7):
        super().__init__()
        self.lstm = nn.LSTM(input_size=input_size, hidden_size=hidden_size, batch_first=True)
        self.fc = nn.Linear(hidden_size, num_classes)

    def forward(self, x):
        B, T, J, C = x.shape
        x = x.view(B, T, J * C)
        out, (h_n, _) = self.lstm(x)
        return self.fc(h_n[-1])