# -*- coding: utf-8 -*-
"""lstm_classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kd_5jWdvJmrZj5SL2vB3_GQzdA_dj-rR
"""

import torch
import torch.nn as nn

class LSTMBehaviorClassifier(nn.Module):
    def __init__(self, input_size, hidden_size=128, num_layers=1, num_classes=2):
        super(LSTMBehaviorClassifier, self).__init__()
        self.lstm = nn.LSTM(input_size=input_size, hidden_size=hidden_size,
                            num_layers=num_layers, batch_first=True)
        self.classifier = nn.Linear(hidden_size, num_classes)

    def forward(self, x):
        output, (hn, cn) = self.lstm(x)
        last_hidden = hn[-1]
        out = self.classifier(last_hidden)
        return out

